### PR TITLE
Feature/args support

### PR DESCRIPTION
**Pull request by jsboige**
This adds supporting command line args in a distinct user .bat to define hostname, port and authentication.

### CODE REVIEW

**Comment by jhj0517** [comment]
Hi @jsboige!
Thank you for your contribution. Does this PR also include "Adding txt support"?
Adding some arguments looks good to me, but I don't understand the purpose of adding the .txt file format. 
You can simply open a .srt file with Notepad, which includes timestamps. 
Is there a use case for this?

**Comment by jhj0517** [comment]
Can you please update this to separate with "Adding txt support"?

**Comment by jsboige** [comment]
I'm sorry I botched up those two, they should definetly be independent. Hopefully I can get you onboard with the txt. Say you want to do a comparison with a poem or a song's lyrics. This the format you then wanna use. Does that make sense?

**Comment by jhj0517** [comment]
If this feature is separated out and there's demand from several people for "Adding txt support", I'll definitely work on it.
I'll keep it open until there's some demand for it. It should be separated from this regardless.

**Comment by jsboige** [comment]
> If this feature is separated out and there's demand from several people for "Adding txt support", I'll definitely work on it. I'll keep it open until there's some demand for it. It should be separated from this regardless.

@jhj0517 No pb, is that OK now?

**Review by jhj0517 — APPROVED** [review]
LGTM! Thank you for your contribution.
merged.

**Pull request merged**
